node {
    stage ('clean'){
         bat label: 'clean', script: 'mvn clean'
    }
      stage('validate') {
        bat label: 'validate', script: 'mvn validate'
    }
    stage('build') {
        bat label: 'build', script: 'mvn build'
    }
    stage('test Stage')
       steps{
           withMaven(maven : 'maven_3_6_3') {
                              bat "mvn test"
                          }
    }
    stage('install stage'){
           steps {
                withMaven(maven : 'maven_6_3_3') {
                    bat 'mvn install'
                }
            }
     
    }
   


        
}
